services:
  ustoearth:
    image: ustoearth/ustoearth:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - PROD_DB_URL=${DEV_DATASOURCE_URL}
      - PROD_DB_USER=${DEV_DATASOURCE_USERNAME}
      - PROD_DB_PASSWORD=${DEV_DATASOURCE_PASSWORD}
      - TZ=Asia/Seoul